Add DirectxTK for windows
xmake-io/xmake-repo pull request #111
Opened 2020-11-06 14:27 UTC by yamashi

2020-11-06 15:09 UTC, waruqi commented on packages/d/directxtk/xmake.lua
> +                    ["20.9.0"]="sept2020"
fix code style: `] = "sept2020"

2020-11-06 15:54 UTC, waruqi commented on packages/d/directxtk/xmake.lua
> +        local configs = { "-DCMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION=" .. package:config("vs_sdkver") }
```lua
local vs_sdkver = get_config("vs_sdkver")
if vs_sdkver then
    table.insert(configs, "-DCMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION=" .. vs_sdkver)
end
```

2020-11-06 16:32 UTC, yamashi commented
Please squash this disaster ^^

2020-11-06 16:55 UTC, SirLynix requested changes

2020-11-06 16:55 UTC, SirLynix commented on packages/d/directxtk/xmake.lua
> +    set_homepage("https://github.com/Tessil/hopscotch-map")
Wrong homepage

2020-11-06 16:55 UTC, SirLynix commented on packages/d/directxtk/xmake.lua
> +            split_version = {};
Using Lua patterns would be an improvement, like `string.match("10.0.19041.0", "%d+%.%d+%.(%d+)%.?%d*")`

2020-11-07 02:04 UTC, waruqi commented on packages/d/directxtk/xmake.lua
> +
Please remove empty lines

2020-11-07 14:34 UTC, waruqi commented on packages/d/directxtk/xmake.lua
> -
please remove unused split function

2020-11-07 14:40 UTC, waruqi commented
In order to avoid too long commit history affecting git pull time, please merge all commit to a single commit.

2020-11-07 14:49 UTC, yamashi commented
> 
> 
> In order to avoid too long commit history affecting git pull time, please merge all commit to a single commit.

You can do a squash merge it will make a single commit

2020-11-07 15:42 UTC, waruqi commented
I have used `git merge --squash directxtk; git commit -a -m "merge directxtk"` to do this squash merge.

But it will lose contributor information。

2020-11-07 15:42 UTC, closed without merging

2020-11-07 16:03 UTC, yamashi commented
Github itself gives you the option to squash merge, you don't need to do it yourself