Improve sdl
xmake-io/xmake-repo pull request #1816
Opened 2023-02-11 15:25 UTC by waruqi

* Before adding new features and new modules, please go to issues to submit the relevant feature description first.
* Write good commit messages and use the same coding conventions as the rest of the project.
* Please commit code to dev branch and we will merge into master branch in feature
* Ensure your edited codes with four spaces instead of TAB.

------

* 增加新特性和新模块之前，请先到issues提交相关特性说明，经过讨论评估确认后，再进行相应的代码提交，避免做无用工作。
* 编写友好可读的提交信息，并使用与工程代码相同的代码规范，代码请用4个空格字符代替tab缩进。
* 请提交代码到dev分支，如果通过，我们会在特定时间合并到master分支上。
* 为了规范化提交日志的格式，commit消息，不要用中文，请用英文描述。

2023-02-12 16:17 UTC, SirLynix commented
I'm very busy for now, but as far as I checked I'd say libsdl_ttf has an issue as zlib may not be the only dependency of freetype, depending on config, we need to pass all libs, but only when freetype is linked statically.

2023-02-13 04:10 UTC, waruqi commented
@SirLynix I have fixed it for mingw, but it does not work for wasm. but it works fine on my machine, I don't know why.

2023-02-13 04:56 UTC, SirLynix commented
> @SirLynix I have fixed it for mingw, and improved libsdl_gfx to support static lib.
> 
> but it does not work for wasm. but it works fine on my machine, I don't know why.

It may be a conflict with wasm builtin libsdl port, try to pass -sUSE_SDL=0 as cxflags?

2023-02-13 07:07 UTC, waruqi commented
> > @SirLynix I have fixed it for mingw, and improved libsdl_gfx to support static lib.
> > but it does not work for wasm. but it works fine on my machine, I don't know why.
> 
> It may be a conflict with wasm builtin libsdl port, try to pass -sUSE_SDL=0 as cxflags?

It works, thanks.

2023-02-13 11:22 UTC, waruqi commented
It works now. ~ @SirLynix

2023-02-13 11:23 UTC, waruqi commented
If there are no other problems, I intend to merge it.

2023-02-13 11:39 UTC, SirLynix requested changes
Linux and macOS don't test all packages because of libsdl_gfx `os.exit()`

2023-02-13 11:39 UTC, SirLynix commented on packages/l/libsdl_gfx/xmake.lua
> +        add_cxflags("-sUSE_SDL=0")
since libsdl_gfx (and others) depends on libsdl which adds this flag already, isn't this redundant?

2023-02-13 11:39 UTC, SirLynix commented on packages/l/libsdl_gfx/xmake.lua
> +        os.exit()
this is unfinished

2023-02-13 11:39 UTC, SirLynix commented on packages/l/libsdl_mixer/xmake.lua
> +        add_cxflags("-sUSE_SDL=0")
same as for libsdl_gfx

2023-02-13 11:39 UTC, SirLynix commented on packages/l/libsdl_image/xmake.lua
> +        add_cxflags("-sUSE_SDL=0")
same as for libsdl_gfx

2023-02-13 11:39 UTC, SirLynix commented on packages/l/libsdl_net/xmake.lua
> +        add_cxflags("-sUSE_SDL=0")
same as for libsdl_gfx

2023-02-13 11:39 UTC, SirLynix commented on packages/l/libsdl_ttf/xmake.lua
> +        add_cxflags("-sUSE_SDL=0")
same as for libsdl_gfx

2023-02-13 13:32 UTC, waruqi commented
> checking for sdl2-config... /Users/runner/.xmake/packages/l/libsdl/2.26.2/54359ddbb6044400b7ce1d91167dd987/bin/sdl2-config
checking for SDL - version >= 2.0.0... no
*** Could not run SDL test program, checking why...
*** The test program compiled, but did not run. This usually means
*** that the run-time linker is not finding SDL or finding the wrong
*** version of SDL. If it is not finding SDL, you'll need to set your
*** LD_LIBRARY_PATH environment variable, or edit /etc/ld.so.conf to point
*** to the installed location  Also, make sure you have run ldconfig if that
*** is required on your system
***
*** If you have an old version installed, it is best to remove it, although
*** you may also be able to get things to work by modifying LD_LIBRARY_PATH


I don't know why?  it works on my machine.

2023-02-13 19:20 UTC, SirLynix commented
I don't get it either, but I don't have a machine with macOS to test it.

2023-02-14 01:28 UTC, waruqi commented
> configure:13134: checking for SDL - version >= 2.0.0
configure:13222: gcc -o conftest  -O -DUSE_MMX -I/Users/runner/.xmake/packages/l/libsdl/2.26.2/54359ddbb6044400b7ce1d91167dd987/include/SDL2 -D_THREAD_SAFE   conftest.c  -L/Users/runner/.xmake/packages/l/libsdl/2.26.2/54359ddbb6044400b7ce1d91167dd987/lib -lSDL2 >&5
ld: warning: dylib (/Users/runner/.xmake/packages/l/libsdl/2.26.2/54359ddbb6044400b7ce1d91167dd987/lib/libSDL2.dylib) was built for newer macOS version (12.6) than being linked (12.0)
configure:13222: $? = 0
configure:13222: ./conftest
dyld[9561]: Library not loaded: '@rpath/libSDL2-2.0.0.dylib'
  Referenced from: '/Users/runner/.xmake/cache/packages/2302/l/libsdl_gfx/1.0.4/source/conftest'
  Reason: tried: '/usr/local/lib/libSDL2-2.0.0.dylib' (no such file), '/usr/lib/libSDL2-2.0.0.dylib' (no such file)
./configure: line 1707:  9561 Abort trap: 6           ./conftest$ac_exeext
configure:13222: $? = 134
configure: program exited with status 134
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""

2023-02-14 11:15 UTC, SirLynix commented
Seems good, thanks! 👍

2023-02-14 11:18 UTC, merged