add libatomic_ops
xmake-io/xmake-repo pull request #4479
Opened 2024-06-26 14:31 UTC by heheda123123

2024-06-26 15:30 UTC, star-hengxing requested changes

2024-06-26 15:30 UTC, star-hengxing commented on packages/l/libatomic_ops/xmake.lua
> +
Missing license

2024-06-26 15:30 UTC, star-hengxing commented on packages/l/libatomic_ops/xmake.lua
> +    add_versions("7.8.2", "d305207fe207f2b3fb5cb4c019da12b44ce3fcbc593dfd5080d867b1a2419b51")
Missing gpl build option
https://github.com/ivmai/libatomic_ops/blob/cc9bc49ae39fcfdf75efb971c74393a313d70491/CMakeLists.txt#L58

2024-06-26 15:30 UTC, star-hengxing commented on packages/l/libatomic_ops/xmake.lua
> +        assert(package:has_cfuncs({test=[[
check_csnippets

2024-06-26 15:30 UTC, star-hengxing commented on packages/l/libatomic_ops/xmake.lua
> +        table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
Missing windows shared lib defines.
https://github.com/ivmai/libatomic_ops/blob/cc9bc49ae39fcfdf75efb971c74393a313d70491/src/atomic_ops.h#L260

2024-06-27 01:38 UTC, heheda123123 commented on packages/l/libatomic_ops/xmake.lua
> +        table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
这里指定了，不用我单独处理把？
https://github.com/ivmai/libatomic_ops/blob/cc9bc49ae39fcfdf75efb971c74393a313d70491/CMakeLists.txt#L128

2024-06-27 01:38 UTC, heheda123123 commented on packages/l/libatomic_ops/xmake.lua
> +        assert(package:has_cfuncs({test=[[
话说，这个是直接复制过来的， https://github.com/xmake-io/xmake-repo/blob/dev/packages/b/bdwgc/xmake.lua
这个也错了

2024-06-27 01:40 UTC, heheda123123 commented on packages/l/libatomic_ops/xmake.lua
> +        assert(package:has_cfuncs({test=[[
改了，等这个库合并了再触发 https://github.com/xmake-io/xmake-repo/pull/4480

2024-06-27 01:54 UTC, star-hengxing commented on packages/l/libatomic_ops/xmake.lua
> +        table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
你可以把这个头文件拷贝下来看看，最终这个宏的值是什么，就知道为什么大部分包都要 package:add(defines

2024-06-27 01:55 UTC, heheda123123 commented on packages/l/libatomic_ops/xmake.lua
> +        table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
你是指给使用者加AO_API？

2024-06-27 02:02 UTC, star-hengxing commented on packages/l/libatomic_ops/xmake.lua
> +        table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
cmake 里面的宏，xmake 不能自动获取，只能包维护者手动加上。
这里我们只需要在 Windows plat 还 shared 的情况下，add defines ao_api=__declspec(dllexport) 或 ao_dll，保证函数都被 __declspec(dllexport) 修饰

2024-07-05 13:36 UTC, merged