add Gtk3 repo source code install
xmake-io/xmake-repo pull request #5154
Opened 2024-09-06 05:35 UTC by hahahahbenny

添加gtk+3 源码安装，但是在测试过程中有一个宏的定义与at-spi2-core中的dbind的定义冲突

2024-09-07 03:45 UTC, star-hengxing requested changes

2024-09-07 03:45 UTC, star-hengxing commented on packages/g/gtk+3/xmake.lua
> +        add_syslinks("pthread", "rt")
glib 已经加了这些，不需要再加了

2024-09-07 03:45 UTC, star-hengxing commented on packages/g/gtk+3/xmake.lua
> +    on_install("linux", "windows", "macosx", function (package)
可以限制只有 linux 构建，其他两个平台移植肯定很麻烦

2024-09-07 03:45 UTC, star-hengxing commented on packages/g/gtk+3/xmake.lua
> +            void test() {
用 `has_cfuncs` 简洁一点

2024-09-11 04:24 UTC, star-hengxing commented
剩下的把 Wayland 选项关了，只允许用 x11 就行

2024-09-11 04:26 UTC, star-hengxing requested changes

2024-09-11 04:26 UTC, star-hengxing commented on packages/a/at-spi2-core/xmake.lua
> +        io.replace(atspi_pkgconfig_dir, "-DG_LOG_DOMAIN=\"dbind\"", "-DG_LOG_DOMAIN=\\\"dbind\\\"")
写成 raw string 就不用转义了

```lua
local atspi_pkgconfig_dir = package:installdir("lib/pkgconfig/atspi-2.pc")
io.replace(atspi_pkgconfig_dir, [[-DG_LOG_DOMAIN="dbind"]], [[-DG_LOG_DOMAIN=\"dbind\"]])
```

2024-09-11 04:26 UTC, star-hengxing commented on packages/g/gtk+3/xmake.lua
>      set_description("Toolkit for creating graphical user interfaces")
gtk+3 应该命名为 gtk3，gtk4 目前也是这样做

2024-09-11 04:29 UTC, hahahahbenny commented
> 剩下的把 Wayland 选项关了，只允许用 x11 就行
 
 但是arch和fedora的报错好像是和gdk-pixbuf有关？

2024-09-11 04:37 UTC, star-hengxing commented
> > 剩下的把 Wayland 选项关了，只允许用 x11 就行
> 
> 但是arch和fedora的报错好像是和gdk-pixbuf有关？

这个可能要我们看一下 https://github.com/xmake-io/xmake/pull/5484#issuecomment-2342451200

2024-09-11 07:45 UTC, hahahahbenny commented
> FAILED: gtk/gtkresources.h 
/github/home/.xmake/packages/g/glib/2.78.1/19890b1935064ee48938a30475bda1a4/bin/glib-compile-resources gtk/gtk.gresources.xml --sourcedir /github/home/.xmake/cache/packages/2409/g/gtk3/3.24.43/source/build_19890b19/gtk --sourcedir /github/home/.xmake/cache/packages/2409/g/gtk3/3.24.43/source/gtk --sourcedir ../gtk --c-name _gtk --internal --generate --target gtk/gtkresources.h --manual-register
**gtk/gtk.gresources.xml: to-pixdata preprocessing requested, but GDK_PIXBUF_PIXDATA is not set, and gdk-pixbuf-pixdata is not in PATH.**

还是存在这个问题，并没有通过禁用wayland得到解决

2024-09-11 07:46 UTC, hahahahbenny commented
我查一下GDK_PIXBUF_PIXDATA和代码中的哪部分相关

2024-09-11 09:29 UTC, star-hengxing commented
> > FAILED: gtk/gtkresources.h
> > /github/home/.xmake/packages/g/glib/2.78.1/19890b1935064ee48938a30475bda1a4/bin/glib-compile-resources gtk/gtk.gresources.xml --sourcedir /github/home/.xmake/cache/packages/2409/g/gtk3/3.24.43/source/build_19890b19/gtk --sourcedir /github/home/.xmake/cache/packages/2409/g/gtk3/3.24.43/source/gtk --sourcedir ../gtk --c-name _gtk --internal --generate --target gtk/gtkresources.h --manual-register
> > **gtk/gtk.gresources.xml: to-pixdata preprocessing requested, but GDK_PIXBUF_PIXDATA is not set, and gdk-pixbuf-pixdata is not in PATH.**
> 
> 还是存在这个问题，并没有通过禁用wayland得到解决, 我去看下源码和GDK_PIXBUF_PIXDATA的关系

估计是要运行 `gdk-pixbuf-pixdata` ，给 `gdk-pixbuf` 包加个 `package:addenv("PATH", "bin")` 就行

2024-09-11 12:48 UTC, hahahahbenny commented
![Snipaste_2024-09-11_20-46-43](https://github.com/user-attachments/assets/a925501a-c390-44fe-8b68-d50c59cbfd72)
在错误命令中并没有cairo安装的另一个include目录

2024-09-11 12:50 UTC, hahahahbenny commented
![image](https://github.com/user-attachments/assets/63da3d2e-1757-42f8-9378-e53f7eb869b6)
在此处应该有另一个include目录

2024-09-11 13:00 UTC, star-hengxing commented
如果库自己导出 `.pc`，xmake 就不会根据我们定义的 `add_includedirs` 生成正确的 `.pc`

- 修复库生成的 `.pc`
- patch gtk 的头文件，像这样 https://github.com/xmake-io/xmake-repo/blob/fd78f60165998aa14e7570abe151a185513da15e/packages/c/c4core/xmake.lua#L35-L40

2024-09-12 05:06 UTC, merged