Ipopt
xmake-io/xmake-repo pull request #5326
Opened 2024-09-24 01:07 UTC by hahahahbenny

添加ipopt包的linux支持

2024-09-24 09:52 UTC, star-hengxing requested changes

2024-09-24 09:52 UTC, star-hengxing commented on packages/i/ipopt/xmake.lua
> +    add_urls("https://github.com/coin-or/Ipopt/archive/refs/tags/releases/3.14.16.tar.gz")
url version 硬编码了

2024-09-24 09:52 UTC, star-hengxing commented on packages/i/ipopt/xmake.lua
> +        add_extsources("apt::liblapack-dev")
放 lapack 包

2024-09-24 09:52 UTC, star-hengxing commented on packages/i/ipopt/xmake.lua
> +package("ipopt")
包名应该也统一 `coin-or-ipopt` 比较好

2024-09-24 09:54 UTC, star-hengxing commented
@waruqi 这里好像没改

```console
error: @programdir/modules/package/tools/autoconf.lua:184: attempt to concatenate a table value (local 'values')
stack traceback:
    [@programdir/modules/package/tools/autoconf.lua:184]: in function '_get_cflags_from_packagedeps'
    [@programdir/modules/package/tools/autoconf.lua:269]: in function 'buildenvs'
    [@programdir/modules/package/tools/autoconf.lua:518]: in function 'configure'
    [@programdir/modules/package/tools/autoconf.lua:564]: in function 'build'
    [@programdir/modules/package/tools/autoconf.lua:593]: in function 'install'
    [/__w/xmake-repo/xmake-repo/packages/i/ipopt/xmake.lua:53]: in function 'script'
    [...dir/modules/private/action/require/impl/utils/filter.lua:114]: in function 'call'
    [.../modules/private/action/require/impl/actions/install.lua:392]:
```

2024-09-26 03:06 UTC, waruqi commented
应该是之前那个 host patch 的改动导致，需要花点时间调下。

2024-09-26 03:30 UTC, hahahahbenny commented
好的👌



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 26, 2024 11:07 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xmake-io/xmake-repo] add Ipopt repo (PR #5326)




 
应该是之前那个 host patch 的改动导致，需要花点时间调下。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2024-09-26 04:16 UTC, star-hengxing commented
> 应该是之前那个 host patch 的改动导致，需要花点时间调下。

不是，还没改之前就是这样了，应该和 meson 之前的改法差不多。

2024-09-26 06:55 UTC, waruqi commented
这个是因为同时依赖了两个 gfortran 包，一个 library 一个 binary 。。

而传入 packagedeps 走 package:dep("gfortran") 只能随机取到一个，错误取到了 binary gfortran 包。。

而 binary gfortran 包的 on_fetch 返回的 信息，不属于库信息，所以 autoconf 里面追加时候，不兼容就报错了。。

2024-09-26 07:00 UTC, star-hengxing requested changes

2024-09-26 07:00 UTC, star-hengxing commented on packages/c/coin-or-ipopt/xmake.lua
> +        lapack_flags = lapack_flags .. [[-lgfortran -lm]]
既然我们这里传了，那 packagedeps 应该可以删了吧

2024-09-26 07:17 UTC, waruqi commented on packages/c/coin-or-ipopt/xmake.lua
> +
多余的空行去掉

2024-09-26 07:26 UTC, waruqi commented on packages/l/lapack/xmake.lua
> +
还有这的空行

2024-09-26 07:27 UTC, waruqi commented on packages/m/mumps/xmake.lua
> +        os.cp("libseq/*h", package:installdir("include"))
`*h` -> `*.h`

2024-09-26 07:27 UTC, waruqi commented on packages/c/coin-or-ipopt/xmake.lua
> +        import("package.tools.autoconf").install(package, configs, {packagedeps={"mumps", "scotch", "lapack", "gfortran"}})
= 两边空格

2024-09-26 07:43 UTC, waruqi commented
https://github.com/xmake-io/xmake/pull/5666 等下这个 patch 


另外，尽可能减少对 packagedeps 的设置，避免 flags 过长

2024-09-26 07:45 UTC, waruqi commented on packages/c/coin-or-ipopt/xmake.lua
> +        import("package.tools.autoconf").install(package, configs, {packagedeps={"mumps", "scotch", "lapack"}})
= 两边空格

2024-09-26 07:45 UTC, waruqi commented on packages/w/wxwidgets/xmake.lua
> +            if is_plat("linux") then
package:is_plat

2024-09-26 07:51 UTC, hahahahbenny commented
> [xmake-io/xmake#5666](https://github.com/xmake-io/xmake/pull/5666) 等下这个 patch
> 
> 另外，尽可能减少对 packagedeps 的设置，避免 flags 过长

好的，刚才提交包含了wxwidgets的修改，提交错了

2024-09-26 09:19 UTC, waruqi commented
可以先把 ipopt 单独先合进来， wxwidget 单独弄。。到时候审核也是挨个 pr 审核的，不要全混一起

2024-09-26 09:24 UTC, hahahahbenny commented
> 可以先把 ipopt 单独先合进来， wxwidget 单独弄。。到时候审核也是挨个 pr 审核的，不要全混一起，也方便合并

好的，我刚才提交的时候把wxwidgets的包含进取了就导致后面的提交被污染了，我重新开一个pr吧

2024-09-26 12:57 UTC, star-hengxing commented
可以把那几个 commit revert

2024-09-26 13:03 UTC, waruqi commented
revert + force push 下就行了

2024-09-26 13:34 UTC, hahahahbenny commented
算了，我还是重新开一个pr吧

2024-09-26 13:34 UTC, closed without merging