add libcanberra repo
xmake-io/xmake-repo pull request #5586
Opened 2024-10-26 17:10 UTC by hahahahbenny

添加libcanberra的repo

2024-10-27 14:07 UTC, waruqi commented on packages/l/libtool/xmake.lua
> +        if package:configs("kind") == "library" then
package:is_library()

2024-10-27 14:08 UTC, waruqi commented on packages/l/libtool/xmake.lua
> +            package:set("kind", "library")
这里怪怪的，没有 kind == library 这个配置项。

2024-10-27 14:13 UTC, hahahahbenny commented on packages/l/libtool/xmake.lua
> +            package:set("kind", "library")
ruki哥，那我通过add_configs来加?

2024-10-27 14:14 UTC, hahahahbenny commented on packages/l/libtool/xmake.lua
> +            package:set("kind", "library")
ruki哥，那应该怎么set_kind呢？

2024-10-27 14:33 UTC, waruqi commented on packages/l/libcanberra/xmake.lua
> +    add_deps("libtool", {configs = {kind_libtool = library}})
https://github.com/xmake-io/xmake-repo/blob/4723e3ec5358d548149fbf03480373dfc2fae750/packages/l/libomp/xmake.lua#L33

2024-10-27 14:33 UTC, waruqi commented on packages/l/libtool/xmake.lua
> +            package:set("kind", "library")
https://github.com/xmake-io/xmake-repo/blob/4723e3ec5358d548149fbf03480373dfc2fae750/packages/l/libomp/xmake.lua#L33

这里不需要做任何设置

2024-10-27 14:48 UTC, hahahahbenny commented
对了，ruki哥，如果自己手动加链接地址或者include地址的话，除了用add_includedir还有什么方法吗？因为如果用add_included加其他包的include地址，得转成相对地址才能加

2024-10-28 01:47 UTC, waruqi commented
> 对了，ruki哥，如果自己手动加链接地址或者include地址的话，除了用add_includedir还有什么方法吗？因为如果用add_included加其他包的include地址，得转成相对地址才能加

只能用于添加当前包的 includedir 和 linkdirs ，为啥要加其他包的。。如果要加，也应该在对应那个包里 通过add_includedir 去导出。。不要在当前包中加其他包的 includedir

2024-10-28 01:49 UTC, waruqi commented on packages/l/libcanberra/xmake.lua
> +        table.insert(configs, "LDFLAGS=-L" .. fetchinfo.artifacts.installdir .. "/lib")
这里不对，fetchinfo 里没  artifacts 。。只有 fetchinfo.linkdirs 和 fetchinfo.sysincludedirs/fetchinfo.includedirs

而且 fetchinfo 可能是 nil 得判空

2024-10-28 01:50 UTC, waruqi commented on packages/l/libcanberra/xmake.lua
> +        local libtool_dir = "../../../libtool" .. after_libtool
路径追加用 path.join

2024-10-28 01:50 UTC, waruqi commented on packages/l/libcanberra/xmake.lua
> +        local after_libtool = string.sub(fetchinfo.artifacts.installdir, pos + 7)
不要直接用 installdir ，fetchinfo 里没这个，

2024-10-28 01:50 UTC, waruqi commented on packages/l/libcanberra/xmake.lua
> +        import("package.tools.autoconf").install(package, configs, {packagedeps= {"libvorbis"}})
= 两边空格

2024-10-28 01:50 UTC, waruqi commented on packages/l/libcanberra/xmake.lua
> +        print(libtool_libdir)
print 去了

2024-10-28 01:51 UTC, waruqi commented on packages/l/libcanberra/xmake.lua
> +        package:add("linkdirs", libtool_dir .. "/lib/")
为啥 libtool 的路径，要在这里导出。怪怪的。。如果 libtool 作为 library，在 add_deps 时候，已经自动对用户导出了。

2024-10-28 01:52 UTC, waruqi commented on packages/l/libtool/xmake.lua
> +            package:set("kind", "library")
这里可以全删了

2024-10-28 02:31 UTC, hahahahbenny commented on packages/l/libtool/xmake.lua
> +            package:set("kind", "library")
ruki哥，如果删了on_load这部分，在构建的时候会报错，
![image](https://github.com/user-attachments/assets/6c745d36-92b9-4752-a85e-4f307c748769)

2024-10-28 02:58 UTC, waruqi commented on packages/l/libcanberra/xmake.lua
> -        table.insert(configs, "CFLAGS=-I" .. fetchinfo.artifacts.installdir .. "/include")
add_includedirs 是导出给 用户侧的，所以要删，这里是传给当前 autoconf 编译用的，如果库自身需要这些信息，就不用删，但是用 artifacts 不对。得从 fetchinfo.linkdirs 和 fetchinfo.sysincludedirs or fetchinfo.includedirs 中去提取路径

2024-10-28 02:59 UTC, waruqi commented on packages/l/libcanberra/xmake.lua
>      add_deps("libvorbis", {configs = {shared=true}})
= 两边空格

2024-10-28 03:04 UTC, hahahahbenny commented on packages/l/libcanberra/xmake.lua
> -        table.insert(configs, "CFLAGS=-I" .. fetchinfo.artifacts.installdir .. "/include")
之前是因为libtool的类型是binary,所以才需要手动加给autoconf，我发现改了autoconf的类型后，可以不用手动加

2024-10-28 05:01 UTC, hahahahbenny commented on packages/l/libcanberra/xmake.lua
> +                table.insert(configs, "LDFLAGS=-L" .. linkdirs)
确实，因为之前只有binary，在packagedeps加不进去，所以就手动加。现在修改

2024-10-28 06:35 UTC, star-hengxing requested changes

2024-10-28 06:35 UTC, star-hengxing commented on packages/l/libcanberra/xmake.lua
> +            package:add("deps", "libvorbis", {configs = {shared = true}})
`add_deps` 只能在 `on_load` 执行

2024-10-28 06:35 UTC, star-hengxing commented on packages/l/libtool/xmake.lua
> +        add_syslinks("dl")
这里要单独放在 `is_plat("linux")`，否则会影响交叉编译

2024-10-28 06:35 UTC, star-hengxing commented on packages/l/libcanberra/xmake.lua
> +        local fetchinfo = package:dep("libtool"):fetch()
漏删了

2024-10-28 06:35 UTC, star-hengxing commented on packages/l/libcanberra/xmake.lua
> +    add_deps("libvorbis", {configs = {shared = true}})
漏删了

2024-10-28 07:39 UTC, waruqi commented on packages/l/libcanberra/xmake.lua
> +    add_links("canberra", "canberra-null", "canberra-alsa", "canberra-oss", "canberra-pulse", "canberra-multi", "ltdl")
ltdl 也是这个包的库么？系统库得用 add_syslinks

2024-10-28 07:40 UTC, waruqi commented on packages/l/libtool/xmake.lua
> +        if package:kind() ~= "library" then
```lua
if not package:is_library() then
```

2024-10-28 07:41 UTC, hahahahbenny commented
ltdl是libtool的库



---Original---
From: ***@***.***&gt;
Date: Mon, Oct 28, 2024 15:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xmake-io/xmake-repo] add libcanberra repo (PR #5586)




 
@waruqi commented on this pull request.
 
 
In packages/l/libcanberra/xmake.lua:
 &gt; +    set_homepage("https://0pointer.de/lennart/projects/libcanberra/") +    set_description("libcanberra is an implementation of the XDG Sound Theme and Name Specifications") +    set_license("LGPL-2.1") + +    add_urls("http://0pointer.de/lennart/projects/libcanberra/libcanberra-$(version).tar.xz") +    add_versions("0.30", "c2b671e67e0c288a69fc33dc1b6f1b534d07882c2aceed37004bf48c601afa72") + +    add_deps("libtool", {kind = "library"}) +    add_deps("autoconf", "automake", "m4") +    add_deps("libogg", "alsa-lib") + +    if is_plat("linux") then +        add_syslinks("dl") +    end + +    add_links("canberra", "canberra-null", "canberra-alsa", "canberra-oss", "canberra-pulse", "canberra-multi", "ltdl")  
ltdl 也是这个包的库么？系统库得用 add_syslinks
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2024-10-28 07:42 UTC, waruqi commented on packages/l/libtool/xmake.lua
> +        end
其实这里你啥也不用改，直接开头 `set_kind("binary")` 就行了，你其他地方改成 library kind，会优先使用覆盖掉的。

2024-10-28 07:42 UTC, waruqi commented on packages/l/libtool/xmake.lua
> +        if package:kind() ~= "binary" then
package:is_binary

2024-10-28 07:43 UTC, waruqi commented on packages/l/libcanberra/xmake.lua
> +    add_links("canberra", "canberra-null", "canberra-alsa", "canberra-oss", "canberra-pulse", "canberra-multi", "ltdl")
这个好像是 libtool 的库，不应该在 libtool 里面自动导出了么

2024-10-28 07:44 UTC, star-hengxing commented on packages/l/libtool/xmake.lua
> +        end
感觉这样改可能也不够通用，如果是 library kind 就加一句 `package:addenv("PATH", "bin")` 应该更好

2024-10-28 07:44 UTC, waruqi commented
> ltdl是libtool的库
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Oct 28, 2024 15:40 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [xmake-io/xmake-repo] add libcanberra repo (PR #5586) @waruqi commented on this pull request. In packages/l/libcanberra/xmake.lua: &gt; + set_homepage("https://0pointer.de/lennart/projects/libcanberra/") + set_description("libcanberra is an implementation of the XDG Sound Theme and Name Specifications") + set_license("LGPL-2.1") + + add_urls("http://0pointer.de/lennart/projects/libcanberra/libcanberra-$(version).tar.xz") + add_versions("0.30", "c2b671e67e0c288a69fc33dc1b6f1b534d07882c2aceed37004bf48c601afa72") + + add_deps("libtool", {kind = "library"}) + add_deps("autoconf", "automake", "m4") + add_deps("libogg", "alsa-lib") + + if is_plat("linux") then + add_syslinks("dl") + end + + add_links("canberra", "canberra-null", "canberra-alsa", "canberra-oss", "canberra-pulse", "canberra-multi", "ltdl") ltdl 也是这个包的库么？系统库得用 add_syslinks — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

那应该 libtool 里面设置 links 而不是这里

2024-10-28 07:53 UTC, star-hengxing commented
那改成这样，能拿到二进制也能拿到 lib/include 信息。

```lua
-- libtool/xmake.lua
on_load(function (package)
    if package:is_library() then
        package:addenv("PATH", "bin")
    end
end)
```

2024-10-28 08:04 UTC, waruqi commented on packages/l/libtool/xmake.lua
> +        end
理论上也可以，不过这个包 大部分情况下都是作为 host toolchain 一部分，走 binary 也许更稳些，我不确定切到 library，是否会有啥副作用。

2024-10-28 09:17 UTC, star-hengxing commented on packages/l/libtool/xmake.lua
> +    set_kind("binary")
```console
fatal error: 'ltdl.h' file not found
#include <ltdl.h>
```
@waruqi 🌚看起来没被下游包影响。。

2024-10-28 09:19 UTC, hahahahbenny commented on packages/l/libtool/xmake.lua
> +    set_kind("binary")
不是，我搞错了，ontest的地方判断反了

2024-10-28 09:19 UTC, hahahahbenny commented on packages/l/libtool/xmake.lua
> +    set_kind("binary")
😂

2024-10-28 10:19 UTC, merged